"""Shared building blocks for the guided estimator wizard.

This package exposes the core validation model, calculation helpers, and
profile persistence utilities so they can be reused by both the CLI wizard
and the new web UI.
"""

from .estimator import (  # noqa: F401
    T4EstimateRequest,
    compute_tax_summary,
    contribution_status,
    estimate_from_t4,
    expected_cpp_contributions,
    expected_ei_contribution,
    round_cents,
    to_decimal,
    within_limit,
)
from .profiles import (  # noqa: F401
    BASE_DIR,
    DEFAULT_PROFILE_FILE,
    PROFILE_HISTORY_DIR,
    PROFILE_TRASH_DIR,
    PROFILES_DIR,
    CLI_BOOL_FIELDS,
    CLI_INT_FIELDS,
    CLI_NUMERIC_FIELDS,
    CLI_SAVE_ORDER,
    CLI_SUBMIT_FIELDS,
    delete_profile,
    get_active_profile,
    list_profiles,
    list_trash,
    load_profile,
    rename_profile,
    restore_profile,
    save_profile_data,
    save_user_data,
    set_active_profile,
    slugify,
)
from .fields import (  # noqa: F401
    canonicalize_data,
    canonicalize_with_metadata,
    coerce_for_field,
    load_data_file,
    parse_bool,
    parse_freeform_text,
    parse_number,
)

__all__ = [
    "T4EstimateRequest",
    "compute_tax_summary",
    "contribution_status",
    "estimate_from_t4",
    "expected_cpp_contributions",
    "expected_ei_contribution",
    "round_cents",
    "to_decimal",
    "within_limit",
    "BASE_DIR",
    "DEFAULT_PROFILE_FILE",
    "PROFILE_HISTORY_DIR",
    "PROFILE_TRASH_DIR",
    "PROFILES_DIR",
    "CLI_BOOL_FIELDS",
    "CLI_INT_FIELDS",
    "CLI_NUMERIC_FIELDS",
    "CLI_SAVE_ORDER",
    "CLI_SUBMIT_FIELDS",
    "delete_profile",
    "get_active_profile",
    "list_profiles",
    "list_trash",
    "load_profile",
    "rename_profile",
    "restore_profile",
    "save_profile_data",
    "save_user_data",
    "set_active_profile",
    "slugify",
    "canonicalize_data",
    "canonicalize_with_metadata",
    "coerce_for_field",
    "load_data_file",
    "parse_bool",
    "parse_freeform_text",
    "parse_number",
]
