from typing import Any


class _LocatorAssertions:
    def to_be_disabled(self, *args: Any, **kwargs: Any) -> None: ...
    def not_to_be_disabled(self, *args: Any, **kwargs: Any) -> None: ...
    def to_have_attribute(self, *args: Any, **kwargs: Any) -> None: ...
    def to_have_text(self, *args: Any, **kwargs: Any) -> None: ...
    def to_have_value(self, *args: Any, **kwargs: Any) -> None: ...
    def to_be_visible(self, *args: Any, **kwargs: Any) -> None: ...
    def to_be_focused(self, *args: Any, **kwargs: Any) -> None: ...


def expect(*args: Any, **kwargs: Any) -> _LocatorAssertions: ...


__all__ = ["expect"]
